name: Table of Contents Generator

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'

concurrency:
  group: ${{ github.workflow }}-$${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: TOC Generator
        uses: technote-space/toc-generator@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_PATHS: "README.md"
